// Generated by Wrangler by running `wrangler types`

// Cloudflare R2 類型定義
interface R2Bucket {
	get(key: string): Promise<R2Object | null>;
	put(key: string, value: string | ArrayBuffer | ArrayBufferView, options?: R2PutOptions): Promise<void>;
	delete(key: string): Promise<void>;
	list(options?: R2ListOptions): Promise<R2ListResult>;
}

interface R2Object {
	key: string;
	size: number;
	etag: string;
	httpEtag: string;
	httpMetadata?: R2HTTPMetadata;
	customMetadata?: Record<string, string>;
	body: ReadableStream;
	text(): Promise<string>;
	json(): Promise<any>;
	arrayBuffer(): Promise<ArrayBuffer>;
}

interface R2PutOptions {
	httpMetadata?: R2HTTPMetadata;
	customMetadata?: Record<string, string>;
	md5?: string;
	sha1?: string;
	sha256?: string;
	sha384?: string;
	sha512?: string;
}

interface R2HTTPMetadata {
	contentType?: string;
	contentLanguage?: string;
	contentDisposition?: string;
	contentEncoding?: string;
	cacheControl?: string;
	cacheExpiry?: string;
}

interface R2ListOptions {
	limit?: number;
	prefix?: string;
	cursor?: string;
	delimiter?: string;
	startAfter?: string;
}

interface R2ListResult {
	objects: R2Object[];
	truncated: boolean;
	cursor?: string;
	delimitedPrefixes: string[];
}

interface Env {
	OPENROUTER_API_KEY: string;
	OPENROUTER_BASE_URL: string;
	OPENROUTER_MODEL: string;
	IS_DEVELOPMENT?: string;
	SENSEMAKER_RESULTS: R2Bucket;
	SENSEMAKER_RESULTS_PREVIEW: R2Bucket;
}
